apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: foundryvtt
  namespace: foundryvtt
spec:
  interval: 5m
  chart:
    spec:
      chart: foundry-vtt
      version: '~0'
      sourceRef:
        kind: HelmRepository
        name: foundryvtt
        namespace: foundryvtt
  values:
    container:
      preserveOwner: '/data/Data.*'
      timezone: 'Europe/Stockholm'
    foundryvtt:
      existingLicenseType: "account"
      existingSecret: foundryvtt-secrets
      existingUserSecret: foundryvtt-secrets
      release_url: blahaj.lgbt
      hostname: "foundry.profanitybandits.net"
      proxyPort: "443"
      proxySSL: true
      s3:
        enabled: true
        existingSecret: foundryvtt-s3
      version: '10.291'
    service:
      tls: false
    persistence:
      enabled: false
    image:
      tag: release
      pullPolicy: Always
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              version: v1
              kind: Deployment
              name: foundryvtt-foundry-vtt
            patch:
              - op: add
                path: /spec/template/spec/containers/0/volumeMounts/-
                value:
                  mountPath: /data
                  name: tmpfiles
              - op: add
                path: /spec/template/spec/containers/0/volumeMounts/-
                value:
                  mountPath: /data/Data
                  name: data
                  mountPropagation: HostToContainer
              - op: add
                path: /spec/template/spec/volumes/-
                value:
                  name: rclone-config
                  secret:
                    secretName: rclone-config
                    items:
                      - key: rclone.conf
                        path: rclone.conf
              - op: add
                path: /spec/template/spec/volumes/-
                value:
                  name: tmpfiles
                  emptyDir: {}
              - op: add
                path: /spec/template/spec/containers/-
                value:
                  image: rclone/rclone
                  name: rclone
                  args:
                    - mount
                    - foundryvtt-s3:foundryvtt-data
                    - /data
                    - --allow-non-empty
                    - --allow-other
                    - --uid
                    - '421'
                    - --gid
                    - '421'
                  volumeMounts:
                    - mountPath: /config/rclone/
                      name: rclone-config
                      readOnly: true
                    - mountPath: /data
                      name: data
                      readOnly: false
                      mountPropagation: Bidirectional
                  securityContext:
                    privileged: true
                    capabilities:
                      add:
                        - SYS_ADMIN
                  resources:
                    limits:
                      cpu: 150m
                      memory: 256Mi
              - op: add
                path: /spec/template/spec/hostAliases
                value:
                  - ip: 10.255.132.92
                    hostnames:
                      - rgw.ctrl-c.liu.se
                      - foundryvtt-data.rgw.ctrl-c.liu.se
