apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: foundryvtt
  namespace: foundryvtt
spec:
  interval: 5m
  chart:
    spec:
      chart: foundry-vtt
      version: '~0'
      sourceRef:
        kind: HelmRepository
        name: foundryvtt
        namespace: foundryvtt
  values:
    foundryvtt:
      existingLicenseType: "account"
      existingSecret: foundryvtt-secrets
      existingUserSecret: foundryvtt-secrets
      release_url: blahaj.lgbt
      hostname: "foundry.profanitybandits.net"
      proxyPort: "443"
      proxySSL: true
      s3:
        enabled: true
        existingSecret: foundryvtt-s3
    service:
      tls: false
    persistence:
      enabled: false
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              version: v1
              kind: Deployment
              name: foundryvtt-foundry-vtt
            patch:
              - op: add
                path: /spec/template/spec/containers/0/volumeMounts/-
                value:
                  mountPath: /data
                  name: data
                  mountPropagation: HostToContainer
              - op: add
                path: /spec/template/spec/volumes/-
                value:
                  name: rclone-config
                  secret:
                    secretName: rclone-config
                    items:
                      - key: rclone.conf
                        path: rclone.conf
              - op: add
                path: /spec/template/spec/containers/-
                value:
                  image: rclone/rclone
                  name: rclone
                  args:
                    - mount
                    - foundryvtt-s3:foundryvtt-data
                    - /data
                  volumeMounts:
                    - mountPath: /config/rclone/
                      name: rclone-config
                      readOnly: true
                    - mountPath: /data
                      name: data
                      readOnly: false
                      mountPropagation: Bidirectional
                  lifecycle:
                    preStop:
                      exec:
                        command:
                          - /bin/sh
                          - -c
                          - fusermount -uz /data
                  securityContext:
                    privileged: true
                    capabilities:
                      add:
                        - SYS_ADMIN
                  resources:
                    limits:
                      cpu: 100m
                      memory: 100Mi
