apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: foundryvtt
  namespace: foundryvtt
spec:
  interval: 5m
  chart:
    spec:
      chart: foundry-vtt
      version: '~0'
      sourceRef:
        kind: HelmRepository
        name: foundryvtt
        namespace: foundryvtt
  values:
    foundryvtt:
      existingLicenseType: "account"
      existingSecret: foundryvtt-secrets
      existingUserSecret: foundryvtt-secrets
      release_url: blahaj.lgbt
      hostname: "foundry.profanitybandits.net"
      proxyPort: "443"
      proxySSL: true
      s3:
        enabled: true
        existingSecret: foundryvtt-s3
    service:
      tls: false
    persistence:
      enabled: false