apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: foundryvtt
  namespace: foundryvtt
spec:
  interval: 5m
  chart:
    spec:
      chart: foundry-vtt
      version: '~0'
      sourceRef:
        kind: HelmRepository
        name: foundryvtt
        namespace: foundryvtt
  values:
    container:
      timezone: 'Europe/Stockholm'
      preserveConfig: true
    foundryvtt:
      existingLicenseType: "account"
      existingSecret: foundryvtt-secrets
      existingUserSecret: foundryvtt-secrets
      release_url: blahaj.lgbt
      hostname: "foundry.profanitybandits.net"
      proxyPort: "443"
      proxySSL: true
      s3:
        enabled: true
        existingSecret: foundryvtt-s3
      version: '13.346' #remember to doublecheck
    service:
      tls: false
    persistence:
      enabled: true
      size: 32Gi
      storageClass: 'rook-ceph'
    image:
      tag: release
      pullPolicy: Always
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              version: v1
              kind: Deployment
              name: foundryvtt-foundry-vtt
            patch:
              - op: add
                path: /spec/template/spec/hostAliases
                value:
                  - ip: 10.255.132.92
                    hostnames:
                      - rgw.ctrl-c.liu.se
                      - foundryvtt-data.rgw.ctrl-c.liu.se
