apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: '~21'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: network #correct namespace.
  values:
    globalArguments:
      - "--global.sendanonymoususage=false"
      - "--global.checknewversion=false"
    additionalArguments:
      - "--serversTransport.insecureSkipVerify=true"
    deployment:
      enabled: true
      replicas: 1
    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
    ingressRoute:
      dashboard:
        enabled: false
    providers:
      kubernetesCRD:
        enabled: true
        ingressClass: traefik-external
      kubernetesIngress:
        enabled: true
        publishedService:
          enabled: false
    rbac:
      enabled: true
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: 130.236.253.195
        allocateLoadBalancerNodePorts: false