apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: '~21'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  valuesFrom:
    - kind: ConfigMap
      name: values
      valuesKey: values.yaml
  service:
    spec:
      allocateLoadBalancerNodePorts: false