apiVersion: v1
kind: ConfigMap
metadata:
  name: continuwuity-config
  namespace: matrix
  labels:
    app.kubernetes.io/name: continuwuity
data:
  continuwuity.toml: |
    [global]
    rocksdb_direct_io = false
    rocksdb_optimize_for_spinning_disks = true
    rocksdb_parallelism_threads = 1
