apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: continuwuity-data
  namespace: matrix
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph
  resources:
    requests:
      storage: 20Gi
