apiVersion: v1
kind: Secret
metadata:
  name: sftpgo-db
  namespace: sftpgo
type: Opaque
stringData:
  postgres-password: REPLACE_POSTGRES_SUPERUSER_PASSWORD
  password: REPLACE_SFTPGO_DB_USER_PASSWORD
