apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: pb-vintagestory-release
    namespace: vintagestory
spec:
    chart:
      spec:
        chart: vintage-story
        reconcileStrategy: ChartVersion
        sourceRef:
          kind: HelmRepository
          name: vintagestory-charts
        version: ~0
    interval: 5m
    values:
        persistence:
            serverfiles:
            enabled: true
            mountPath: /vintagestory
        portal:
            open:
            enabled: true
        securityContext:
            container:
                readOnlyRootFilesystem: false
                runAsGroup: 0
                runAsUser: 0
        service:
            main:
            ports:
                main:
                port: 42420
                protocol: tcp
                targetPort: 42420
        workload:
            main:
            podSpec:
                containers:
                main:
                    env:
                    GAME_PARAMS: ""
                    VS_CHANNEL: stable
