apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stalwart-mailserver
  namespace: mailserver
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: stalwart-mail
      version: "~1.0.6"
      sourceRef:
        kind: HelmRepository
        name: stalwart-charts
        namespace: mailserver
  values:
    replicaCount: 1

    image:
      registry: ghcr.io
      repository: stalwartlabs/stalwart
      tag: "v0.15.5"

    ingress:
      enabled: false

    traefik:
      enabled: false

    certificate:
      certmanager:
        enabled: false

    nats:
      enabled: false

    backup:
      enabled: false

    config:
      http:
        use-x-forwarded: true
      cluster:
        node-id: "0"
      server:
        hostname: mail.sax.lgbt

    persistence:
      enabled: true
      size: 10Gi

  postRenderers:
    - kustomize:
        patches:
          - target:
              group: apps
              version: v1
              kind: StatefulSet
              name: stalwart-mailserver
            patch: |
              - op: remove
                path: /spec/ordinals
              - op: add
                path: /spec/serviceName
                value: stalwart-mailserver
          - target:
              group: apps
              version: v1
              kind: StatefulSet
              name: stalwart-mailserver
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/envFrom/-
                value:
                  secretRef:
                    name: stalwart-helm-env
