apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: stalwart-charts
  namespace: mailserver
spec:
  interval: 5m
  type: oci
  url: oci://codeberg.org/wrenix/helm-charts
