apiVersion: v1
kind: Secret
metadata:
  name: stalwart-mail-private-values
  namespace: mailserver
type: Opaque
stringData:
  values.yaml: |
    secrets:
      env:
        FALLBACK_ADMIN_SECRET: "REPLACE_ME"
        METRICS_USERNAME: "metrics"
        METRICS_SECRET: "REPLACE_ME"
