apiVersion: v1
kind: Secret
metadata:
  name: stalwart-helm-env
  namespace: mailserver
type: Opaque
stringData:
  FALLBACK_ADMIN_SECRET: "REPLACE_ME"
  METRICS_USERNAME: "metrics"
  METRICS_SECRET: "REPLACE_ME"
