apiVersion: v1
kind: Secret
metadata:
  name: stalwart-mail-private-values
  namespace: mailserver
type: Opaque
stringData:
  values.yaml: |
    secrets:
      env:
        FALLBACK_ADMIN_SECRET: "<redacted>"
        METRICS_USERNAME: "<redacted>"
        METRICS_SECRET: "<redacted>"
