apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pb-minecraft-release
  namespace: minecraft
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft
      version: '4.7.3'
      sourceRef:
        kind: HelmRepository
        name: minecraft-repo
        namespace: minecraft
  values:
    startupProbe:
      enabled: true
      failureThreshold: 360
    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 4Gi
        cpu: 2000m
    minecraftServer:
      eula: "TRUE"
      version: "1.18.2"
      type: "FTBA"
      ftbModpackId: 100
      ftbModpackVersionId: 1.6.1
      difficulty: hard
      whitelist: Sax1337
      ops: Sax1337
      maxPlayers: 20
      maxWorldSize: 500000
      maxBuildHeight: 512
      motd: "Its a Sax Server running Stoneblock 3!"
      servicePort: 25565
      serviceType: LoadBalancer
      externalTrafficPolicy: Local
      externalIPs: null
      worldSaveName: stoneblock3
    persistence:
      dataDir:
        enabled: true
        size: 20Gi
    extraEnv:
      # recommended rolling logs for saving disk
      ENABLE_ROLLING_LOGS: true
      ENABLE_WHITELIST: true
      ENFORCE_WHITELIST: true
      FORCE_WORLD_COPY: false
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              version: v1
              kind: Service
              name: pb-minecraft-release-minecraft
            patch:
              - op: add
                path: /spec/allocateLoadBalancerNodePorts
                value: false