apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pb-minecraft-release
  namespace: minecraft
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft
      version: '4.7.2'
      sourceRef:
        kind: HelmRepository
        name: minecraft-repo
        namespace: minecraft
  values:
    resources:
      requests:
        memory: 4096Mi
        cpu: 1000m
    minecraftServer:
      eula: "TRUE"
      version: "1.18.2"
      type: "FTBA"
      ftbModpackId: "100"
      ftbModpackVersionId: "1.6.1"
      difficulty: hard
      whitelist: Sax1337
      ops: Sax1337
      maxPlayers: 20
      maxWorldSize: 500000
      maxBuildHeight: 512
      motd: "Welcome to Sax's StoneBlock 3 server!"
      servicePort: 25565
      serviceType: LoadBalancer
      generatorSettings:
        worldSaveName: stoneblock3
    persistence:
      dataDir:
        enabled: true
        size: 20Gi
