apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pb-minecraft-release
  namespace: minecraft
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft
      version: '4.7.3'
      sourceRef:
        kind: HelmRepository
        name: minecraft-repo
        namespace: minecraft
  values:
    resources:
      requests:
        memory: 512Mi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1000m
    minecraftServer:
      eula: "TRUE"
      version: "1.18.2"
      type: "FTBA"
      ftbModpackId: 100
      ftbModpackVersionId: 1.6.1
      difficulty: hard
      whitelist: Sax1337
      ops: Sax1337
      maxPlayers: 20
      maxWorldSize: 500000
      maxBuildHeight: 512
      motd: "Its a Sax Server running Stoneblock 3!"
      servicePort: 25565
      serviceType: LoadBalancer
      loadBalancerIP: 130.236.253.195
      nodePort: null
      externalIPs: null
      generatorSettings:
        worldSaveName: stoneblock3
    persistence:
      dataDir:
        enabled: true
        size: 20Gi
    extraEnv:
      # recommended rolling logs for saving disk
      ENABLE_ROLLING_LOGS: true
      ENABLE_WHITELIST: true
      ENFORCE_WHITELIST: true
      FORCE_WORLD_COPY: false
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: service
              name: pb-minecraft-release-minecraft
            patch:
              spec:
                allocateNodePorts: FALSE
