apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pb-minecraft-release
  namespace: minecraft
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft
      version: '4.17.0'
      sourceRef:
        kind: HelmRepository
        name: minecraft-repo
        namespace: minecraft
  values:
    startupProbe:
      enabled: true
      failureThreshold: 360
    resources:
      requests:
        memory: 16384Mi
        cpu: 2000m
      limits:
        memory: 32768Mi
        cpu: 8000m
    minecraftServer:
      eula: "TRUE"
      memory: 16384M
      version: "1.19.2"
      type: "AUTO_CURSEFORGE"
      autoCurseForge:
        apiKey:
          existingSecret: "curse-api"
          secretKey: ProfanityBandits
        excludeMods: [913587, "ryoamiclights"]
        pageUrl: "https://www.curseforge.com/minecraft/modpacks/steam-punk"
        parallelDownloads: 4
        overridesSkipExisting: false
      difficulty: normal
      whitelist: Saxie
      ops: Saxie
      maxPlayers: 20
      maxWorldSize: 5000000
      maxBuildHeight: 512
      motd: "Sax's SteamPunk Server! Choo-Choo!"
      servicePort: 25565
      serviceType: LoadBalancer
      externalTrafficPolicy: Local
      externalIPs: null
      worldSaveName: steampunk
    persistence:
      dataDir:
        enabled: true
        Size: 40Gi
    extraEnv:
      # recommended rolling logs for saving disk
      ENABLE_ROLLING_LOGS: true
      ENABLE_WHITELIST: true
      ENFORCE_WHITELIST: true
      FORCE_WORLD_COPY: false
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              version: v1
              kind: Service
              name: pb-minecraft-release-minecraft
            patch:
              - op: add
                path: /spec/allocateLoadBalancerNodePorts
                value: false