apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pb-minecraft-release #Test
  namespace: minecraft
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft
      version: '4.7.2'
      sourceRef:
        kind: HelmRepository
        name: minecraft-repo
        namespace: minecraft
  values:
    resources:
      requests:
        memory: 4096Mi
        cpu: 1000m
    minecraftServer:
      eula: "TRUE"
      version: "1.19.4"
      difficulty: normal
      whitelist: Sax1337
      ops: Sax1337
      maxPlayers: 20
      maxWorldSize: 50000
      maxBuildHeight: 512
      motd: "Welcome to Sax's Test Server!"
      generatorSettings:
        worldSaveName: test
      persistence:
        dataDir:
          enabled: true
          size: 10Gi