apiVersion: apps/v1
kind: Deployment
metadata:
  name: tes3mp-server
  namespace: tes3mp
spec:
  replicas: 1
  strategy:
    type: Recreate #Doesn't work?
  selector:
    matchLabels:
        tes3mp: server
  template:
    metadata:
        labels:
          tes3mp: server
    spec:
      volumes:
        - name: tes3mp-data
          persistentVolumeClaim:
            claimName: tes3mp-storage
      resources: 
        requests:
          memory: 4096Mi
          cpu: 500m
        limits:
          memory: 8192Mi
          cpu: 2000m
      containers:
        - name: tes3mp-server
          image: grimkriegor/tes3mp-forge
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /build
              subPath: build
              name: tes3mp-data
              readOnly: false
            - mountPath: /data
              subPath: data
              name: tes3mp-data
              readOnly: false
              #Do I remove --make-package?
          args: ["--version", "0.8.1", "--install", "--server-only"]
          resources:
            limits:
              memory: 8192Mi
              cpu: 2000m