apiVersion: v1
kind: Service
metadata:
  name: tes3mp-server-service
  namespace: tes3mp
spec:
   type: NodePort
   selector:
      tes3mp: server
   ports:
      - port: 25565
        targetPort: 25565
        nodePort: 25566